# CFSI configuration file
# Lines starting with # are ignored

config_file:
  version: 0.1.0
  has_secrets: false
  store_secrets: true

secrets:
  AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY

logging:
  log_level: 10  # 10: debug, 20: info, 30: warn, 40: error, 50: critical

index:
  s2_index:
    s3_buckets: [  # List of S3 buckets to use for indexing.
        "sentinel-s2-l1c",
        "sentinel-s2-l2a",
    ]
    grids: [  # List of Sentinel-2 grids to index
        "35PNM",
        "35PPM",
        "35PQM",
        "35PNL",
        "35PPL",
        "35PQL",
    ]
    months: [  # List of months to index
        "9",
        "10",
    ]
    years: [  # List of years to index
        "2020"
    ]

masks:
  # Cloud mask generation configuration

  # Maximum and minimum cloudiness percentages in Sentinel-2 tile metadata.
  # Tiles with cloudiness percentages above or below the threshold are
  # skipped, and no cloud/shadow masks are generated for them.
  # Setting these to 100.0 and 0.0 means no tiles are skipped.
  max_cloud_threshold: 100.0
  min_cloud_threshold: 0.0

  write_rgb: true                  # write l1c rgb for validating results
  write_l1c: false                 # write l1c all bands for validating results

  s2cloudless_masks:
    generate: true                # generate s2cloudless masks
    cloud_threshold: 0.3           # cloud threshold value for s2cloudless
    cloud_projection_distance: 30  # maximum distance to search for cloud shadows in 10m pixels
    dark_pixel_threshold: 0.25     # max band 8 value for pixel to be considered dark
    max_iterations: 0              # max. nr. of cloud masks to create at once. 0 = unlimited

  fmask_masks:
    generate: true                 # generate fmask masks
    max_iterations: 0              # max. nr. of cloud masks to create at once. 0 = unlimited

mosaic:
  # Mosaic creator configuration

  # Dates is a list of dates in YYYY-MM-DD format specifying the days for which
  # mosaics are created. A special keyword of "today" is also accepted.
  # An output mosaic is generated for each entry.
  dates: [
      "2020-09-30",
      "2020-10-30",
  ]

  # List of cloud/shadow mask products to use for creating mosaics.
  # An output mosaic is generated for each entry.
  products: [
      "s2a_level1c_s2cloudless",
  ]

  # Range defines the maximum range (in days) to look for cloudless pixels.
  # E.g. a value of 90 means images from up to 90 days before the day specified
  # in the "dates" list above are taken into account when creating a mosaic.
  # A higher value will reduce the chance of cloudy areas in the mosaic, at the
  # cost of performance and recentness.
  range: 60
  recentness: 1          # Recentness band: 0: don't create, 1: create for first band, 2: create for all bands
  output_bands: [        # List of bands to include in the mosaic product
      "B02_10m",
      "B03_10m",
      "B04_10m",
  ]
  write_original: false  # Write original S2-L2A output images
