version: "3"
services:
    odc:
        build: .
        env_file:
            .env
        environment:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - CFSI_CONTAINER_OUTPUT=/output
            - CFSI_OUTPUT_DIR
        depends_on:
            - db
        networks:
            - cfsi
        volumes:
            - ${CFSI_OUTPUT_HOST}:${CFSI_OUTPUT_CONTAINER}
            - ${CFSI_CONFIG_FILE}:${CFSI_BASE_CONTAINER}/${CFSI_CONFIG_FILE}
    db:
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        image: postgis/postgis:${POSTGIS_VERSION_TAG}
        networks:
            - cfsi
        ports:
            - ${DB_PORT}:5432
        restart: always

networks:
    cfsi:
        driver: bridge
