version: "3"
services:
    odc:
        build: .
        environment:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - CFSI_CONTAINER_OUTPUT=/output
            - CFSI_OUTPUT_PROTOCOL=FILE
            - CFSI_OUTPUT_DIR
        depends_on:
            - db
        networks:
            - cfsi
        volumes:
            - ${CFSI_OUTPUT_DIR}:/output
    db:
        environment:
            POSTGRES_USER: opendatacube
            POSTGRES_PASSWORD: opendatacube
        image: postgis/postgis:13-3.1
        networks:
            - cfsi
        ports:
            - 5432:5432
        restart: always

networks:
    cfsi:
        driver: bridge
