version: "3"
services:
    odc:
        build: .
        environment:
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - CFSI_OUTPUT_DIR=/output
        depends_on:
            - db
        volumes:
            - ./output:/output
    db:
        image: postgres:13
        restart: always
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: opendatacube
            POSTGRES_PASSWORD: opendatacube
