AWS_AMI_ID = "ami-0502e817a62226e03"
CFSI_BASE_HOST = "/home/ubuntu/cfsi"
CFSI_BRANCH = "master"
CFSI_OUTPUT_HOST = "/home/ubuntu/cfsi_output"
CFSI_REPOSITORY = "https://github.com/GispoCoding/CFSI.git"
CFSI_USER_HOST = "ubuntu"
OWS_BRANCH = "cfsi"
